# Generated by Django 2.0.2 on 2019-11-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=60, verbose_name='Apellido')),
                ('dni', models.CharField(help_text='Dni válido ej. 22222222', max_length=8)),
                ('direccion', models.CharField(help_text='Ej. Rosario 2000', max_length=100, verbose_name='Localidad')),
                ('telefono', models.CharField(max_length=18)),
                ('email', models.EmailField(max_length=254)),
                ('procurador', models.CharField(choices=[('NO', 'NO'), ('SI', 'SI')], max_length=2)),
                ('codigocurso', models.CharField(blank=True, max_length=7)),
                ('nombrecurso', models.CharField(blank=True, max_length=60)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Suscriptor',
                'verbose_name_plural': 'Suscriptores',
            },
        ),
    ]
