# Generated by Django 2.0.2 on 2019-11-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='institucion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Institución organizadora'),
        ),
        migrations.AlterField(
            model_name='page',
            name='order',
            field=models.SmallIntegerField(default=0, help_text='1 Es el principal, luego a partir del 2 son secundarios<br>Recuerde no repetir nunca valores es decir establezca un orden ordinal<br> ej si son 2 cursos el principal sera 1 y el secundario 2, si son 3 cursos el principal 1, luego 2 y luego 3<br>Si el curso que carga es antiguo es decir ya finalizo puede poner cualquier numero sin seguir un orden<br>este campo sirve para ordenar todos los cursos actuales o futuros a ese efecto<br>debe establecer los nros en cada curso para que se muestren los activos secundarios y el curso principal que desee mostrar.', verbose_name='Orden de publicación'),
        ),
    ]
