# Generated by Django 2.0.2 on 2021-01-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20191112_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='institucion',
            field=models.CharField(blank=True, help_text='Solo rellene este campo si el curso no es organizado por el IAPP', max_length=200, null=True, verbose_name='Institución organizadora'),
        ),
    ]
